-- ============================================================
-- 修复 b_project_all：当前/累计「数量 vs 金额」过滤不一致
-- F_Id = 2026051508433100001
--
-- 问题：
-- 1) project_num/company_num 排除整个「国方二期」
-- 2) total_amount 却保留「国方二期 + 母基金直投」
-- 3) ct_amount 又包含「国方二期 + 子基金」穿透
-- → 卡片上底层数量与投资/穿透金额不是同一批项目
--
-- 修复后统一口径：
-- - 排除 国方一期产品
-- - 排除 国方二期「子基金」底层（与一期重叠），保留国方二期母基金直投
-- - 当前数量：net_cost > 0
-- - 当前 total_amount / sh_amount / csj_amount / pd_amount：net_cost > 0 时用 cost
-- - 当前 ct_amount：net_cost > 0 时用 net_cost_1（穿透仍按剩余）
-- - 当前 ipo_amount（上市企业）：net_cost > 0 时用 net_cost_1（穿透金额）
-- - 累计 ipo_amount_a（上市企业）：用 cost_1（穿透成本）
-- - 累计其它：同一基金过滤，金额用 cost / cost_1
--
-- 生产执行方式二选一：
-- A) 用业绩看板「数据接口」打开 b_project_all，粘贴同目录
--    04_修复_b_project_all_完整sql.sql 后保存，再重建版本
-- B) 或执行下面 UPDATE（内容太长时优先 A）
-- ============================================================

-- 校验：修复后试跑（把 ${date} 换成 '2026-09-30'）应看到
-- project_num / company_num / total_amount / ct_amount 来自同一过滤条件
