/** 自动生成：同步业绩看板导出表字段 COMMENT（含 -数字 排序标记） */
const ALTER_SQL = [
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN F_Id varchar(50) NOT NULL COMMENT '主键';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN F_CreatorUserId varchar(50) NULL DEFAULT NULL COMMENT '创建用户';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN F_CreatorTime datetime NULL DEFAULT NULL COMMENT '创建时间';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN F_DeleteUserId varchar(50) NULL DEFAULT NULL COMMENT '删除用户';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN F_DeleteMark int NOT NULL DEFAULT 0 COMMENT '删除状态';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN F_DeleteTime datetime NULL DEFAULT NULL COMMENT '删除时间';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN version varchar(300) NULL DEFAULT NULL COMMENT '版本号-2';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN b_date datetime NULL DEFAULT NULL COMMENT '时间条件-1';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN inv_amount decimal(30,10) NULL DEFAULT NULL COMMENT '投资金额/实缴-14';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN moc decimal(30,10) NULL DEFAULT NULL COMMENT 'MOC-16';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN girr decimal(30,10) NULL DEFAULT NULL COMMENT 'GIRR-17';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN nirr decimal(30,10) NULL DEFAULT NULL COMMENT 'NIRR-12';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN paidin decimal(30,10) NULL DEFAULT NULL COMMENT '投资人实缴-7';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN distribution decimal(30,10) NULL DEFAULT NULL COMMENT '投资人分配-8';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN dpi decimal(30,10) NULL DEFAULT NULL COMMENT 'DPI-10';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN rvpi decimal(30,10) NULL DEFAULT NULL COMMENT 'RVPI-11';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN tvpi decimal(30,10) NULL DEFAULT NULL COMMENT 'TVPI-9';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN fund varchar(300) NULL DEFAULT NULL COMMENT '基金名称-3';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN sub_amount decimal(30,10) NULL DEFAULT NULL COMMENT '投资金额/认缴-13';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN lp_sub decimal(30,10) NULL DEFAULT NULL COMMENT '投资人认缴-6';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN exit_amount decimal(30,10) NULL DEFAULT NULL COMMENT '退出金额-15';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN fund_type varchar(300) NULL DEFAULT NULL COMMENT '基金类型-4';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN set_up_date datetime NULL DEFAULT NULL COMMENT '成立时间-5';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN F_Lock int NULL DEFAULT 0 COMMENT '锁定状态';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN d_moc decimal(30,10) NULL DEFAULT NULL COMMENT '直投整体MOC-18';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN d_dpi decimal(30,10) NULL DEFAULT NULL COMMENT '直投DPI-19';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN d_paid decimal(30,10) NULL DEFAULT NULL COMMENT '直投实缴-20';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN d_receive decimal(30,10) NULL DEFAULT NULL COMMENT '直投回款-21';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN sf_moc decimal(30,10) NULL DEFAULT NULL COMMENT '子基金整体MOC-24';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN sf_dpi decimal(30,10) NULL DEFAULT NULL COMMENT '子基金DPI-25';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN sf_paid decimal(30,10) NULL DEFAULT NULL COMMENT '子基金实缴-26';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN sf_receive decimal(30,10) NULL DEFAULT NULL COMMENT '子基金回款-27';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN d_unrealized decimal(30,10) NULL DEFAULT NULL COMMENT '直投未实现价值-22';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN dt_value decimal(30,10) NULL DEFAULT NULL COMMENT '直投总价值-23';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN sf_unrealized decimal(30,10) NULL DEFAULT NULL COMMENT '子基金未实现价值-28';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN sft_value decimal(30,10) NULL DEFAULT NULL COMMENT '子基金总价值-29';",
  "ALTER TABLE b_transaction_indicator MODIFY COLUMN net_asset decimal(30,10) NULL DEFAULT NULL COMMENT '资本账户-30';",
  "ALTER TABLE b_investor_list MODIFY COLUMN F_Id varchar(50) NOT NULL COMMENT '主键';",
  "ALTER TABLE b_investor_list MODIFY COLUMN F_CreatorUserId varchar(50) NULL DEFAULT NULL COMMENT '创建用户';",
  "ALTER TABLE b_investor_list MODIFY COLUMN F_CreatorTime datetime NULL DEFAULT NULL COMMENT '创建时间';",
  "ALTER TABLE b_investor_list MODIFY COLUMN F_DeleteUserId varchar(50) NULL DEFAULT NULL COMMENT '删除用户';",
  "ALTER TABLE b_investor_list MODIFY COLUMN F_DeleteMark int NULL DEFAULT 0 COMMENT '删除状态';",
  "ALTER TABLE b_investor_list MODIFY COLUMN F_DeleteTime datetime NULL DEFAULT NULL COMMENT '删除时间';",
  "ALTER TABLE b_investor_list MODIFY COLUMN version varchar(300) NULL DEFAULT NULL COMMENT '版本号-2';",
  "ALTER TABLE b_investor_list MODIFY COLUMN b_date datetime NULL DEFAULT NULL COMMENT '时间条件-1';",
  "ALTER TABLE b_investor_list MODIFY COLUMN fund varchar(300) NULL DEFAULT NULL COMMENT '基金名称-3';",
  "ALTER TABLE b_investor_list MODIFY COLUMN lp varchar(300) NULL DEFAULT NULL COMMENT '投资人名称-5';",
  "ALTER TABLE b_investor_list MODIFY COLUMN subscription_amount decimal(30,10) NULL DEFAULT NULL COMMENT '认缴金额-6';",
  "ALTER TABLE b_investor_list MODIFY COLUMN subscription_ratio decimal(30,10) NULL DEFAULT NULL COMMENT '认缴比例-7';",
  "ALTER TABLE b_investor_list MODIFY COLUMN distribution decimal(30,10) NULL DEFAULT NULL COMMENT '累计分配金额-9';",
  "ALTER TABLE b_investor_list MODIFY COLUMN paidin decimal(30,10) NULL DEFAULT NULL COMMENT '累计实缴金额-8';",
  "ALTER TABLE b_investor_list MODIFY COLUMN first_date datetime NULL DEFAULT NULL COMMENT '第N次分配时间-10';",
  "ALTER TABLE b_investor_list MODIFY COLUMN first_amount decimal(30,10) NULL DEFAULT NULL COMMENT '第N次分配金额-11';",
  "ALTER TABLE b_investor_list MODIFY COLUMN second_date datetime NULL DEFAULT NULL COMMENT '第N-1次分配时间-12';",
  "ALTER TABLE b_investor_list MODIFY COLUMN second_amount decimal(30,10) NULL DEFAULT NULL COMMENT '第N-1次分配金额-13';",
  "ALTER TABLE b_investor_list MODIFY COLUMN third_date datetime NULL DEFAULT NULL COMMENT '第N-2次分配时间-14';",
  "ALTER TABLE b_investor_list MODIFY COLUMN third_amount decimal(30,10) NULL DEFAULT NULL COMMENT '第N-2次分配金额-15';",
  "ALTER TABLE b_investor_list MODIFY COLUMN lp_type varchar(300) NULL DEFAULT NULL COMMENT '投资人类型-4';",
  "ALTER TABLE b_investor_list MODIFY COLUMN F_Lock int NULL DEFAULT 0 COMMENT '锁定状态';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN F_Id varchar(50) NOT NULL COMMENT '主键';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN F_CreatorUserId varchar(50) NULL DEFAULT NULL COMMENT '创建用户';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN F_CreatorTime datetime NULL DEFAULT NULL COMMENT '创建时间';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN F_DeleteUserId varchar(50) NULL DEFAULT NULL COMMENT '删除用户';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN F_DeleteMark int NULL DEFAULT 0 COMMENT '删除状态';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN F_DeleteTime datetime NULL DEFAULT NULL COMMENT '删除时间';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN version varchar(300) NULL DEFAULT NULL COMMENT '版本号-02';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN b_date datetime NULL DEFAULT NULL COMMENT '时间条件-01';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN fund varchar(300) NULL DEFAULT NULL COMMENT '基金名称-03';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN fund_inv int NULL DEFAULT NULL COMMENT '子基金投资数量-06';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN fund_exit int NULL DEFAULT NULL COMMENT '子基金退出数量-07';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN fund_sub decimal(30,10) NULL DEFAULT NULL COMMENT '子基金认缴金额-08';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN fund_exit_amount decimal(30,10) NULL DEFAULT NULL COMMENT '子基金退出金额-09';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN fund_paidin decimal(30,10) NULL DEFAULT NULL COMMENT '子基金实缴金额-10';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN fund_receive decimal(30,10) NULL DEFAULT NULL COMMENT '子基金回款金额-11';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN project_inv int NULL DEFAULT NULL COMMENT '直投项目投资数量-12';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN project_exit int NULL DEFAULT NULL COMMENT '直投项目退出数量-13';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN project_paidin decimal(30,10) NULL DEFAULT NULL COMMENT '直投项目实缴金额-14';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN project_receive decimal(30,10) NULL DEFAULT NULL COMMENT '直投项目回款金额-15';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN fund_type varchar(300) NULL DEFAULT NULL COMMENT '基金类型-04';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN set_up_date datetime NULL DEFAULT NULL COMMENT '成立时间-05';",
  "ALTER TABLE b_investment_indicator MODIFY COLUMN F_Lock int NULL DEFAULT 0 COMMENT '锁定状态';",
  "ALTER TABLE b_investment MODIFY COLUMN F_Id varchar(50) NOT NULL COMMENT '主键';",
  "ALTER TABLE b_investment MODIFY COLUMN F_CreatorUserId varchar(50) NULL DEFAULT NULL COMMENT '创建用户';",
  "ALTER TABLE b_investment MODIFY COLUMN F_CreatorTime datetime NULL DEFAULT NULL COMMENT '创建时间';",
  "ALTER TABLE b_investment MODIFY COLUMN F_DeleteUserId varchar(50) NULL DEFAULT NULL COMMENT '删除用户';",
  "ALTER TABLE b_investment MODIFY COLUMN F_DeleteMark int NULL DEFAULT 0 COMMENT '删除状态';",
  "ALTER TABLE b_investment MODIFY COLUMN F_DeleteTime datetime NULL DEFAULT NULL COMMENT '删除时间';",
  "ALTER TABLE b_investment MODIFY COLUMN fund varchar(300) NULL DEFAULT NULL COMMENT '基金名称-04';",
  "ALTER TABLE b_investment MODIFY COLUMN version varchar(300) NULL DEFAULT NULL COMMENT '版本号-02';",
  "ALTER TABLE b_investment MODIFY COLUMN b_date datetime NULL DEFAULT NULL COMMENT '时间条件-01';",
  "ALTER TABLE b_investment MODIFY COLUMN transaction_type varchar(300) NULL DEFAULT NULL COMMENT '投资类别-06';",
  "ALTER TABLE b_investment MODIFY COLUMN acc_sub decimal(30,10) NULL DEFAULT NULL COMMENT '认缴金额累计-09';",
  "ALTER TABLE b_investment MODIFY COLUMN change_sub decimal(30,10) NULL DEFAULT NULL COMMENT '认缴金额本月变动-10';",
  "ALTER TABLE b_investment MODIFY COLUMN acc_paidin decimal(30,10) NULL DEFAULT NULL COMMENT '实缴金额累计-11';",
  "ALTER TABLE b_investment MODIFY COLUMN change_paidin decimal(30,10) NULL DEFAULT NULL COMMENT '实缴金额本月变动-12';",
  "ALTER TABLE b_investment MODIFY COLUMN acc_exit decimal(30,10) NULL DEFAULT NULL COMMENT '退出金额累计-13';",
  "ALTER TABLE b_investment MODIFY COLUMN change_exit decimal(30,10) NULL DEFAULT NULL COMMENT '退出金额本月变动-14';",
  "ALTER TABLE b_investment MODIFY COLUMN acc_receive decimal(30,10) NULL DEFAULT NULL COMMENT '回款金额累计-15';",
  "ALTER TABLE b_investment MODIFY COLUMN change_receive decimal(30,10) NULL DEFAULT NULL COMMENT '回款金额本月变动-16';",
  "ALTER TABLE b_investment MODIFY COLUMN project varchar(300) NULL DEFAULT NULL COMMENT '项目名称-07';",
  "ALTER TABLE b_investment MODIFY COLUMN first_date datetime NULL DEFAULT NULL COMMENT '首次投资时间-08';",
  "ALTER TABLE b_investment MODIFY COLUMN fund_type varchar(300) NULL DEFAULT NULL COMMENT '基金类型-03';",
  "ALTER TABLE b_investment MODIFY COLUMN set_up_date datetime NULL DEFAULT NULL COMMENT '成立时间-05';",
  "ALTER TABLE b_investment MODIFY COLUMN unrealized decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '未实现价值-17';",
  "ALTER TABLE b_investment MODIFY COLUMN change_unrealized decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '未实现价值变动-18';",
  "ALTER TABLE b_investment MODIFY COLUMN total_value decimal(30,10) NULL DEFAULT NULL COMMENT '总价值-19';",
  "ALTER TABLE b_investment MODIFY COLUMN moc decimal(30,10) NULL DEFAULT NULL COMMENT 'MOC-20';",
  "ALTER TABLE b_investment MODIFY COLUMN dpi decimal(30,10) NULL DEFAULT NULL COMMENT 'DPI-21';",
  "ALTER TABLE b_investment MODIFY COLUMN F_Lock int NULL DEFAULT 0 COMMENT '锁定状态';",
  "ALTER TABLE b_investment MODIFY COLUMN acc_exit_profit decimal(30,10) NULL DEFAULT NULL COMMENT '累计退出收益-23';",
  "ALTER TABLE b_investment MODIFY COLUMN acc_exit_capital decimal(30,10) NULL DEFAULT NULL COMMENT '累计退出成本-22';",
  "ALTER TABLE b_investment MODIFY COLUMN acc_dividend decimal(30,10) NULL DEFAULT NULL COMMENT '其中:累计分红-24';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN F_Id varchar(50) NOT NULL COMMENT '主键';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN F_CreatorUserId varchar(50) NULL DEFAULT NULL COMMENT '创建用户';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN F_CreatorTime datetime NULL DEFAULT NULL COMMENT '创建时间';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN F_LastModifyTime datetime NULL DEFAULT NULL COMMENT '最后修改时间';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN F_DeleteUserId varchar(50) NULL DEFAULT NULL COMMENT '删除用户';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN F_DeleteMark int NULL DEFAULT 0 COMMENT '删除状态';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN F_DeleteTime datetime NULL DEFAULT NULL COMMENT '删除时间';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN version varchar(300) NULL DEFAULT NULL COMMENT '版本号-02';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN b_date datetime NULL DEFAULT NULL COMMENT '时间条件-01';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN transaction_type varchar(300) NULL DEFAULT NULL COMMENT '投资类别-03';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN acc_sub decimal(30,10) NULL DEFAULT NULL COMMENT '认缴金额累计-05';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN change_sub decimal(30,10) NULL DEFAULT NULL COMMENT '认缴金额本月变动-06';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN acc_paidin decimal(30,10) NULL DEFAULT NULL COMMENT '实缴金额累计-07';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN change_paidin decimal(30,10) NULL DEFAULT NULL COMMENT '实缴金额本月变动-08';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN acc_exit decimal(30,10) NULL DEFAULT NULL COMMENT '退出金额累计-09';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN change_exit decimal(30,10) NULL DEFAULT NULL COMMENT '退出金额本月变动-10';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN acc_receive decimal(30,10) NULL DEFAULT NULL COMMENT '回款金额累计-11';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN change_receive decimal(30,10) NULL DEFAULT NULL COMMENT '回款金额本月变动-12';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN project varchar(300) NULL DEFAULT NULL COMMENT '项目名称-04';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN unrealized decimal(30,10) NULL DEFAULT NULL COMMENT '未实现价值-13';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN change_unrealized decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '未实现价值变动-14';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN total_value decimal(30,10) NULL DEFAULT NULL COMMENT '总价值-15';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN moc decimal(30,10) NULL DEFAULT NULL COMMENT 'MOC-16';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN dpi decimal(30,10) NULL DEFAULT NULL COMMENT 'DPI-17';",
  "ALTER TABLE b_investment_sum MODIFY COLUMN F_Lock int NULL DEFAULT 0 COMMENT '锁定状态';",
  "ALTER TABLE b_manage MODIFY COLUMN F_Id varchar(50) NOT NULL COMMENT '主键';",
  "ALTER TABLE b_manage MODIFY COLUMN F_CreatorUserId varchar(50) NULL DEFAULT NULL COMMENT '创建用户';",
  "ALTER TABLE b_manage MODIFY COLUMN F_CreatorTime datetime NULL DEFAULT NULL COMMENT '创建时间';",
  "ALTER TABLE b_manage MODIFY COLUMN F_DeleteUserId varchar(50) NULL DEFAULT NULL COMMENT '删除用户';",
  "ALTER TABLE b_manage MODIFY COLUMN F_DeleteMark int NULL DEFAULT 0 COMMENT '删除状态';",
  "ALTER TABLE b_manage MODIFY COLUMN F_DeleteTime datetime NULL DEFAULT NULL COMMENT '删除时间';",
  "ALTER TABLE b_manage MODIFY COLUMN fund varchar(300) NULL DEFAULT NULL COMMENT '基金名称-04';",
  "ALTER TABLE b_manage MODIFY COLUMN fund_type varchar(300) NULL DEFAULT NULL COMMENT '基金类型-03';",
  "ALTER TABLE b_manage MODIFY COLUMN sub_amount decimal(30,10) NULL DEFAULT NULL COMMENT '认缴规模-06';",
  "ALTER TABLE b_manage MODIFY COLUMN paid_in_amount decimal(30,10) NULL DEFAULT NULL COMMENT '实缴规模-08';",
  "ALTER TABLE b_manage MODIFY COLUMN dis_amount decimal(30,10) NULL DEFAULT NULL COMMENT '累计分配金额-10';",
  "ALTER TABLE b_manage MODIFY COLUMN version varchar(300) NULL DEFAULT NULL COMMENT '版本号-02';",
  "ALTER TABLE b_manage MODIFY COLUMN b_date datetime NULL DEFAULT NULL COMMENT '时间条件-01';",
  "ALTER TABLE b_manage MODIFY COLUMN set_up_date datetime NULL DEFAULT NULL COMMENT '成立时间-05';",
  "ALTER TABLE b_manage MODIFY COLUMN F_Lock int NULL DEFAULT 0 COMMENT '锁定状态';",
  "ALTER TABLE b_manage MODIFY COLUMN sub_add decimal(30,10) NULL DEFAULT NULL COMMENT '本年新增认缴-07';",
  "ALTER TABLE b_manage MODIFY COLUMN paid_in_add decimal(30,10) NULL DEFAULT NULL COMMENT '本年新增实缴-09';",
  "ALTER TABLE b_manage MODIFY COLUMN dis_add decimal(30,10) NULL DEFAULT NULL COMMENT '本年新增分配-11';",
  "ALTER TABLE b_transaction MODIFY COLUMN F_Id varchar(50) NOT NULL COMMENT '主键';",
  "ALTER TABLE b_transaction MODIFY COLUMN F_CreatorUserId varchar(50) NULL DEFAULT NULL COMMENT '创建用户';",
  "ALTER TABLE b_transaction MODIFY COLUMN F_CreatorTime datetime NULL DEFAULT NULL COMMENT '创建时间';",
  "ALTER TABLE b_transaction MODIFY COLUMN F_DeleteUserId varchar(50) NULL DEFAULT NULL COMMENT '删除用户';",
  "ALTER TABLE b_transaction MODIFY COLUMN F_DeleteMark int NULL DEFAULT 0 COMMENT '删除状态';",
  "ALTER TABLE b_transaction MODIFY COLUMN F_DeleteTime datetime NULL DEFAULT NULL COMMENT '删除时间';",
  "ALTER TABLE b_transaction MODIFY COLUMN fund varchar(300) NULL DEFAULT NULL COMMENT '基金名称-03';",
  "ALTER TABLE b_transaction MODIFY COLUMN spv varchar(300) NULL DEFAULT NULL COMMENT 'spv名称-05';",
  "ALTER TABLE b_transaction MODIFY COLUMN sub_fund varchar(300) NULL DEFAULT NULL COMMENT '子基金名称-06';",
  "ALTER TABLE b_transaction MODIFY COLUMN company varchar(300) NULL DEFAULT NULL COMMENT '被投企业名称-07';",
  "ALTER TABLE b_transaction MODIFY COLUMN transaction_type varchar(300) NULL DEFAULT NULL COMMENT '交易类型-08';",
  "ALTER TABLE b_transaction MODIFY COLUMN transaction_amount decimal(30,10) NULL DEFAULT NULL COMMENT '交易金额-10';",
  "ALTER TABLE b_transaction MODIFY COLUMN version varchar(300) NULL DEFAULT NULL COMMENT '版本号-02';",
  "ALTER TABLE b_transaction MODIFY COLUMN lp varchar(300) NULL DEFAULT NULL COMMENT '投资人名称-04';",
  "ALTER TABLE b_transaction MODIFY COLUMN transaction_date datetime NULL DEFAULT NULL COMMENT '交易时间-09';",
  "ALTER TABLE b_transaction MODIFY COLUMN b_date datetime NULL DEFAULT NULL COMMENT '时间条件-01';",
  "ALTER TABLE b_transaction MODIFY COLUMN F_Lock int NULL DEFAULT 0 COMMENT '锁定状态';",
  "ALTER TABLE b_transaction MODIFY COLUMN company_name varchar(300) NULL DEFAULT NULL COMMENT '被投企业全称-16';",
  "ALTER TABLE b_transaction MODIFY COLUMN sub_fund_name varchar(300) NULL DEFAULT NULL COMMENT '子基金全称-17';",
  "ALTER TABLE b_transaction MODIFY COLUMN capital decimal(30,10) NULL DEFAULT NULL COMMENT '分配成本-11';",
  "ALTER TABLE b_transaction MODIFY COLUMN profit decimal(30,10) NULL DEFAULT NULL COMMENT '分配收益-12';",
  "ALTER TABLE b_transaction MODIFY COLUMN dividend decimal(30,10) NULL DEFAULT NULL COMMENT '其中:分红-13';",
  "ALTER TABLE b_ipo MODIFY COLUMN F_Id varchar(50) NOT NULL COMMENT '主键';",
  "ALTER TABLE b_ipo MODIFY COLUMN F_CreatorUserId varchar(50) NULL DEFAULT NULL COMMENT '创建用户';",
  "ALTER TABLE b_ipo MODIFY COLUMN F_CreatorTime datetime NULL DEFAULT NULL COMMENT '创建时间';",
  "ALTER TABLE b_ipo MODIFY COLUMN F_LastModifyTime datetime NULL DEFAULT NULL COMMENT '最后修改时间';",
  "ALTER TABLE b_ipo MODIFY COLUMN F_DeleteUserId varchar(50) NULL DEFAULT NULL COMMENT '删除用户';",
  "ALTER TABLE b_ipo MODIFY COLUMN F_DeleteMark int NULL DEFAULT 0 COMMENT '删除状态';",
  "ALTER TABLE b_ipo MODIFY COLUMN F_DeleteTime datetime NULL DEFAULT NULL COMMENT '删除时间';",
  "ALTER TABLE b_ipo MODIFY COLUMN b_date datetime NULL DEFAULT NULL COMMENT '时间条件-01';",
  "ALTER TABLE b_ipo MODIFY COLUMN version varchar(300) NULL DEFAULT NULL COMMENT '版本号-02';",
  "ALTER TABLE b_ipo MODIFY COLUMN project varchar(300) NULL DEFAULT NULL COMMENT '项目简称-05';",
  "ALTER TABLE b_ipo MODIFY COLUMN fund varchar(300) NULL DEFAULT NULL COMMENT '所属基金-03';",
  "ALTER TABLE b_ipo MODIFY COLUMN amount decimal(30,10) NULL DEFAULT NULL COMMENT '投资金额-09';",
  "ALTER TABLE b_ipo MODIFY COLUMN ipo_date datetime NULL DEFAULT NULL COMMENT '上市日期-08';",
  "ALTER TABLE b_ipo MODIFY COLUMN fund_type varchar(300) NULL DEFAULT NULL COMMENT '基金类型-04';",
  "ALTER TABLE b_ipo MODIFY COLUMN F_Lock int NULL DEFAULT 0 COMMENT '锁定状态';",
  "ALTER TABLE b_ipo MODIFY COLUMN stock_name varchar(300) NULL DEFAULT NULL COMMENT '股票简称-06';",
  "ALTER TABLE b_ipo MODIFY COLUMN stock_num varchar(300) NULL DEFAULT NULL COMMENT '股票代码-07';",
  "ALTER TABLE b_ipo_a MODIFY COLUMN F_Id varchar(50) NOT NULL COMMENT '主键';",
  "ALTER TABLE b_ipo_a MODIFY COLUMN F_CreatorUserId varchar(50) NULL DEFAULT NULL COMMENT '创建用户';",
  "ALTER TABLE b_ipo_a MODIFY COLUMN F_CreatorTime datetime NULL DEFAULT NULL COMMENT '创建时间';",
  "ALTER TABLE b_ipo_a MODIFY COLUMN F_DeleteUserId varchar(50) NULL DEFAULT NULL COMMENT '删除用户';",
  "ALTER TABLE b_ipo_a MODIFY COLUMN F_DeleteMark int NULL DEFAULT 0 COMMENT '删除状态';",
  "ALTER TABLE b_ipo_a MODIFY COLUMN F_DeleteTime datetime NULL DEFAULT NULL COMMENT '删除时间';",
  "ALTER TABLE b_ipo_a MODIFY COLUMN b_date datetime NULL DEFAULT NULL COMMENT '时间条件-01';",
  "ALTER TABLE b_ipo_a MODIFY COLUMN version varchar(300) NULL DEFAULT NULL COMMENT '版本号-02';",
  "ALTER TABLE b_ipo_a MODIFY COLUMN project varchar(300) NULL DEFAULT NULL COMMENT '项目简称-05';",
  "ALTER TABLE b_ipo_a MODIFY COLUMN fund varchar(300) NULL DEFAULT NULL COMMENT '所属基金-03';",
  "ALTER TABLE b_ipo_a MODIFY COLUMN amount decimal(30,10) NULL DEFAULT NULL COMMENT '投资金额-09';",
  "ALTER TABLE b_ipo_a MODIFY COLUMN ipo_date datetime NULL DEFAULT NULL COMMENT '上市日期-08';",
  "ALTER TABLE b_ipo_a MODIFY COLUMN fund_type varchar(300) NULL DEFAULT NULL COMMENT '基金类型-04';",
  "ALTER TABLE b_ipo_a MODIFY COLUMN F_Lock int NULL DEFAULT 0 COMMENT '锁定状态';",
  "ALTER TABLE b_ipo_a MODIFY COLUMN stock_num varchar(300) NULL DEFAULT NULL COMMENT '股票代码-07';",
  "ALTER TABLE b_ipo_a MODIFY COLUMN stock_name varchar(300) NULL DEFAULT NULL COMMENT '股票简称-06';",
  "ALTER TABLE b_project MODIFY COLUMN F_Id varchar(50) NOT NULL COMMENT '主键';",
  "ALTER TABLE b_project MODIFY COLUMN F_CreatorUserId varchar(50) NULL DEFAULT NULL COMMENT '创建用户';",
  "ALTER TABLE b_project MODIFY COLUMN F_CreatorTime datetime NULL DEFAULT NULL COMMENT '创建时间';",
  "ALTER TABLE b_project MODIFY COLUMN F_DeleteUserId varchar(50) NULL DEFAULT NULL COMMENT '删除用户';",
  "ALTER TABLE b_project MODIFY COLUMN F_DeleteMark int NULL DEFAULT 0 COMMENT '删除状态';",
  "ALTER TABLE b_project MODIFY COLUMN F_DeleteTime datetime NULL DEFAULT NULL COMMENT '删除时间';",
  "ALTER TABLE b_project MODIFY COLUMN fund varchar(300) NULL DEFAULT NULL COMMENT '基金名称-03';",
  "ALTER TABLE b_project MODIFY COLUMN company_num int NULL DEFAULT NULL COMMENT '被投企业数量-07';",
  "ALTER TABLE b_project MODIFY COLUMN ipo_num int NULL DEFAULT NULL COMMENT '上市企业数量-15';",
  "ALTER TABLE b_project MODIFY COLUMN csj_num int NULL DEFAULT NULL COMMENT '长三角企业数量-10';",
  "ALTER TABLE b_project MODIFY COLUMN total_amount decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '总投资金额-08';",
  "ALTER TABLE b_project MODIFY COLUMN b_date datetime NULL DEFAULT NULL COMMENT '时间条件-01';",
  "ALTER TABLE b_project MODIFY COLUMN version varchar(300) NULL DEFAULT NULL COMMENT '版本号-02';",
  "ALTER TABLE b_project MODIFY COLUMN fund_type varchar(300) NULL DEFAULT NULL COMMENT '基金类型-05';",
  "ALTER TABLE b_project MODIFY COLUMN set_up_date datetime NULL DEFAULT NULL COMMENT '成立时间-04';",
  "ALTER TABLE b_project MODIFY COLUMN sh_num int NULL DEFAULT NULL COMMENT '上海项目数量-14';",
  "ALTER TABLE b_project MODIFY COLUMN ipo_amount decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '上市企业投资金额-16';",
  "ALTER TABLE b_project MODIFY COLUMN project_num int NULL DEFAULT NULL COMMENT '投资项目数量-06';",
  "ALTER TABLE b_project MODIFY COLUMN sh_amount decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '上海项目投资金额-13';",
  "ALTER TABLE b_project MODIFY COLUMN project_amount decimal(30,10) NULL DEFAULT NULL COMMENT '穿透投资金额-09';",
  "ALTER TABLE b_project MODIFY COLUMN csj_amount decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '长三角地区投资金额-11';",
  "ALTER TABLE b_project MODIFY COLUMN F_Lock int NULL DEFAULT 0 COMMENT '锁定状态';",
  "ALTER TABLE b_project_a MODIFY COLUMN F_Id varchar(50) NOT NULL COMMENT '主键';",
  "ALTER TABLE b_project_a MODIFY COLUMN F_CreatorUserId varchar(50) NULL DEFAULT NULL COMMENT '创建用户';",
  "ALTER TABLE b_project_a MODIFY COLUMN F_CreatorTime datetime NULL DEFAULT NULL COMMENT '创建时间';",
  "ALTER TABLE b_project_a MODIFY COLUMN F_DeleteUserId varchar(50) NULL DEFAULT NULL COMMENT '删除用户';",
  "ALTER TABLE b_project_a MODIFY COLUMN F_DeleteMark int NULL DEFAULT 0 COMMENT '删除状态';",
  "ALTER TABLE b_project_a MODIFY COLUMN F_DeleteTime datetime NULL DEFAULT NULL COMMENT '删除时间';",
  "ALTER TABLE b_project_a MODIFY COLUMN fund varchar(300) NULL DEFAULT NULL COMMENT '基金名称-03';",
  "ALTER TABLE b_project_a MODIFY COLUMN company_num int NULL DEFAULT NULL COMMENT '被投企业数量-07';",
  "ALTER TABLE b_project_a MODIFY COLUMN total_amount decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '总投资金额-08';",
  "ALTER TABLE b_project_a MODIFY COLUMN ipo_num int NULL DEFAULT NULL COMMENT '上市企业数量-10';",
  "ALTER TABLE b_project_a MODIFY COLUMN ipo_amount decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '上市企业投资金额-11';",
  "ALTER TABLE b_project_a MODIFY COLUMN project_num int NULL DEFAULT NULL COMMENT '投资项目数量-06';",
  "ALTER TABLE b_project_a MODIFY COLUMN project_amount decimal(30,10) NULL DEFAULT NULL COMMENT '穿透金额-09';",
  "ALTER TABLE b_project_a MODIFY COLUMN b_date datetime NULL DEFAULT NULL COMMENT '时间条件-01';",
  "ALTER TABLE b_project_a MODIFY COLUMN version varchar(300) NULL DEFAULT NULL COMMENT '版本号-02';",
  "ALTER TABLE b_project_a MODIFY COLUMN set_up_date datetime NULL DEFAULT NULL COMMENT '成立时间-04';",
  "ALTER TABLE b_project_a MODIFY COLUMN fund_type varchar(300) NULL DEFAULT NULL COMMENT '基金类型-05';",
  "ALTER TABLE b_project_a MODIFY COLUMN F_Lock int NULL DEFAULT 0 COMMENT '锁定状态';",
  "ALTER TABLE b_region MODIFY COLUMN F_Id varchar(50) NOT NULL COMMENT '主键';",
  "ALTER TABLE b_region MODIFY COLUMN F_CreatorUserId varchar(50) NULL DEFAULT NULL COMMENT '创建用户';",
  "ALTER TABLE b_region MODIFY COLUMN F_CreatorTime datetime NULL DEFAULT NULL COMMENT '创建时间';",
  "ALTER TABLE b_region MODIFY COLUMN F_DeleteUserId varchar(50) NULL DEFAULT NULL COMMENT '删除用户';",
  "ALTER TABLE b_region MODIFY COLUMN F_DeleteMark int NULL DEFAULT 0 COMMENT '删除状态';",
  "ALTER TABLE b_region MODIFY COLUMN F_DeleteTime datetime NULL DEFAULT NULL COMMENT '删除时间';",
  "ALTER TABLE b_region MODIFY COLUMN version varchar(300) NULL DEFAULT NULL COMMENT '版本号-02';",
  "ALTER TABLE b_region MODIFY COLUMN b_date datetime NULL DEFAULT NULL COMMENT '时间条件-01';",
  "ALTER TABLE b_region MODIFY COLUMN fund varchar(300) NULL DEFAULT NULL COMMENT '基金名称-03';",
  "ALTER TABLE b_region MODIFY COLUMN fund_type varchar(300) NULL DEFAULT NULL COMMENT '基金类型-05';",
  "ALTER TABLE b_region MODIFY COLUMN set_up_date datetime NULL DEFAULT NULL COMMENT '成立时间-04';",
  "ALTER TABLE b_region MODIFY COLUMN csj_num int NULL DEFAULT NULL COMMENT '长三角地区企业数量-08';",
  "ALTER TABLE b_region MODIFY COLUMN csj_amount decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '长三角地区企业投资金额-10';",
  "ALTER TABLE b_region MODIFY COLUMN sh_num int NULL DEFAULT NULL COMMENT '上海地区企业数量-13';",
  "ALTER TABLE b_region MODIFY COLUMN sh_amount decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '上海地区投资金额-15';",
  "ALTER TABLE b_region MODIFY COLUMN pd_num int NULL DEFAULT NULL COMMENT '浦东地区企业数量-18';",
  "ALTER TABLE b_region MODIFY COLUMN pd_amount decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '浦东地区投资金额-20';",
  "ALTER TABLE b_region MODIFY COLUMN F_Lock int NULL DEFAULT 0 COMMENT '锁定状态';",
  "ALTER TABLE b_region MODIFY COLUMN t_amount decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '总投资金额-07';",
  "ALTER TABLE b_region MODIFY COLUMN sh_num_ratio decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '上海数量占比-14';",
  "ALTER TABLE b_region MODIFY COLUMN sh_amount_ratio decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '上海金额占比-16';",
  "ALTER TABLE b_region MODIFY COLUMN csj_num_ratio decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '长三角数量占比-09';",
  "ALTER TABLE b_region MODIFY COLUMN csj_amount_ratio decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '长三角金额占比-11';",
  "ALTER TABLE b_region MODIFY COLUMN pd_num_ratio decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '浦东数量占比-19';",
  "ALTER TABLE b_region MODIFY COLUMN pd_amount_ratio decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '浦东金额占比-21';",
  "ALTER TABLE b_region MODIFY COLUMN t_num int NULL DEFAULT NULL COMMENT '总项目数量-06';",
  "ALTER TABLE b_region MODIFY COLUMN csj_amount_ct decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '长三角地区金额_穿透-12';",
  "ALTER TABLE b_region MODIFY COLUMN sh_amount_ct decimal(30,10) NULL DEFAULT NULL COMMENT '上海地区金额_穿透-17';",
  "ALTER TABLE b_region MODIFY COLUMN pd_amount_ct decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '浦东地区金额_穿透-22';",
  "ALTER TABLE b_region_a MODIFY COLUMN F_Id varchar(50) NOT NULL COMMENT '主键';",
  "ALTER TABLE b_region_a MODIFY COLUMN F_CreatorUserId varchar(50) NULL DEFAULT NULL COMMENT '创建用户';",
  "ALTER TABLE b_region_a MODIFY COLUMN F_CreatorTime datetime NULL DEFAULT NULL COMMENT '创建时间';",
  "ALTER TABLE b_region_a MODIFY COLUMN F_DeleteUserId varchar(50) NULL DEFAULT NULL COMMENT '删除用户';",
  "ALTER TABLE b_region_a MODIFY COLUMN F_DeleteMark int NULL DEFAULT 0 COMMENT '删除状态';",
  "ALTER TABLE b_region_a MODIFY COLUMN F_DeleteTime datetime NULL DEFAULT NULL COMMENT '删除时间';",
  "ALTER TABLE b_region_a MODIFY COLUMN version varchar(300) NULL DEFAULT NULL COMMENT '版本号-02';",
  "ALTER TABLE b_region_a MODIFY COLUMN b_date datetime NULL DEFAULT NULL COMMENT '时间条件-01';",
  "ALTER TABLE b_region_a MODIFY COLUMN fund varchar(300) NULL DEFAULT NULL COMMENT '基金名称-03';",
  "ALTER TABLE b_region_a MODIFY COLUMN fund_type varchar(300) NULL DEFAULT NULL COMMENT '基金类型-05';",
  "ALTER TABLE b_region_a MODIFY COLUMN set_up_date datetime NULL DEFAULT NULL COMMENT '成立时间-04';",
  "ALTER TABLE b_region_a MODIFY COLUMN csj_num int NULL DEFAULT NULL COMMENT '长三角地区企业数量-08';",
  "ALTER TABLE b_region_a MODIFY COLUMN csj_amount decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '长三角地区企业投资金额-10';",
  "ALTER TABLE b_region_a MODIFY COLUMN sh_num int NULL DEFAULT NULL COMMENT '上海地区企业数量-13';",
  "ALTER TABLE b_region_a MODIFY COLUMN sh_amount decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '上海地区投资金额-15';",
  "ALTER TABLE b_region_a MODIFY COLUMN pd_num int NULL DEFAULT NULL COMMENT '浦东地区企业数量-18';",
  "ALTER TABLE b_region_a MODIFY COLUMN pd_amount decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '浦东地区投资金额-20';",
  "ALTER TABLE b_region_a MODIFY COLUMN F_Lock int NULL DEFAULT 0 COMMENT '锁定状态';",
  "ALTER TABLE b_region_a MODIFY COLUMN t_amount decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '总投资金额-07';",
  "ALTER TABLE b_region_a MODIFY COLUMN sh_num_ratio decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '上海数量占比-14';",
  "ALTER TABLE b_region_a MODIFY COLUMN sh_amount_ratio decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '上海金额占比-16';",
  "ALTER TABLE b_region_a MODIFY COLUMN csj_num_ratio decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '长三角数量占比-09';",
  "ALTER TABLE b_region_a MODIFY COLUMN csj_amount_ratio decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '长三角金额占比-11';",
  "ALTER TABLE b_region_a MODIFY COLUMN pd_num_ratio decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '浦东数量占比-19';",
  "ALTER TABLE b_region_a MODIFY COLUMN pd_amount_ratio decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '浦东金额占比-21';",
  "ALTER TABLE b_region_a MODIFY COLUMN t_num int NULL DEFAULT NULL COMMENT '总项目数量-06';",
  "ALTER TABLE b_region_a MODIFY COLUMN csj_amount_ct decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '长三角地区金额_穿透-12';",
  "ALTER TABLE b_region_a MODIFY COLUMN sh_amount_ct decimal(30,10) NULL DEFAULT NULL COMMENT '上海地区金额_穿透-17';",
  "ALTER TABLE b_region_a MODIFY COLUMN pd_amount_ct decimal(30,10) NULL DEFAULT '0.0000000000' COMMENT '浦东地区金额_穿透-22';",
  "ALTER TABLE b_manage_indicator MODIFY COLUMN spv_num int NULL DEFAULT NULL COMMENT 'SPV数量_备案';",
  "ALTER TABLE b_all_indicator MODIFY COLUMN spv_paidin decimal(30,10) NULL DEFAULT NULL COMMENT 'SPV累计投资金额';",
  "ALTER TABLE b_all_indicator MODIFY COLUMN spv_receive decimal(30,10) NULL DEFAULT NULL COMMENT 'SPV累计回款金额';",
  "ALTER TABLE b_investment_spv MODIFY COLUMN F_Id varchar(50) NOT NULL COMMENT '主键';",
  "ALTER TABLE b_investment_spv MODIFY COLUMN F_CreatorUserId varchar(50) NULL DEFAULT NULL COMMENT '创建用户';",
  "ALTER TABLE b_investment_spv MODIFY COLUMN F_CreatorTime datetime NULL DEFAULT NULL COMMENT '创建时间';",
  "ALTER TABLE b_investment_spv MODIFY COLUMN F_DeleteUserId varchar(50) NULL DEFAULT NULL COMMENT '删除用户';",
  "ALTER TABLE b_investment_spv MODIFY COLUMN F_DeleteMark int NULL DEFAULT 0 COMMENT '删除状态';",
  "ALTER TABLE b_investment_spv MODIFY COLUMN F_DeleteTime datetime NULL DEFAULT NULL COMMENT '删除时间';",
  "ALTER TABLE b_investment_spv MODIFY COLUMN b_date datetime NULL DEFAULT NULL COMMENT '时间条件-01';",
  "ALTER TABLE b_investment_spv MODIFY COLUMN version varchar(300) NULL DEFAULT NULL COMMENT '版本号-2';",
  "ALTER TABLE b_investment_spv MODIFY COLUMN fund varchar(300) NULL DEFAULT NULL COMMENT '基金名称-3';",
  "ALTER TABLE b_investment_spv MODIFY COLUMN fund_type varchar(300) NULL DEFAULT NULL COMMENT '基金类型-4';",
  "ALTER TABLE b_investment_spv MODIFY COLUMN set_up_date datetime NULL DEFAULT NULL COMMENT '成立时间-5';",
  "ALTER TABLE b_investment_spv MODIFY COLUMN transaction_type varchar(300) NULL DEFAULT NULL COMMENT '投资类别-6';",
  "ALTER TABLE b_investment_spv MODIFY COLUMN project varchar(300) NULL DEFAULT NULL COMMENT '项目名称-7';",
  "ALTER TABLE b_investment_spv MODIFY COLUMN first_date datetime NULL DEFAULT NULL COMMENT '首次投资时间-8';",
  "ALTER TABLE b_investment_spv MODIFY COLUMN acc_sub decimal(30,10) NULL DEFAULT NULL COMMENT '认缴金额累计-9';",
  "ALTER TABLE b_investment_spv MODIFY COLUMN acc_paidin decimal(30,10) NULL DEFAULT NULL COMMENT '实缴金额累计-10';",
  "ALTER TABLE b_investment_spv MODIFY COLUMN acc_exit decimal(30,10) NULL DEFAULT NULL COMMENT '退出金额累计-11';",
  "ALTER TABLE b_investment_spv MODIFY COLUMN acc_receive decimal(30,10) NULL DEFAULT NULL COMMENT '回款金额累计-12';",
  "ALTER TABLE b_investment_spv MODIFY COLUMN F_Lock int NULL DEFAULT 0 COMMENT '锁定状态';",
  "ALTER TABLE b_indicator_describe MODIFY COLUMN spv_num_desc text NULL COMMENT 'SPV数量_备案';",
  "ALTER TABLE b_indicator_describe MODIFY COLUMN spv_paidin_acc_desc text NULL COMMENT 'SPV累计投资金额';",
  "ALTER TABLE b_indicator_describe MODIFY COLUMN spv_receive_acc_desc text NULL COMMENT 'SPV累计回款金额';",
  "ALTER TABLE b_all_indicator MODIFY COLUMN lm_spv_paidin decimal(30,10) NULL DEFAULT NULL COMMENT '上月SPV累计投资金额';",
  "ALTER TABLE b_all_indicator MODIFY COLUMN spv_paidin_change decimal(30,10) NULL DEFAULT NULL COMMENT 'SPV累计投资金额变动';",
  "ALTER TABLE b_all_indicator MODIFY COLUMN lm_spv_receive decimal(30,10) NULL DEFAULT NULL COMMENT '上月SPV累计回款金额';",
  "ALTER TABLE b_all_indicator MODIFY COLUMN spv_receive_change decimal(30,10) NULL DEFAULT NULL COMMENT 'SPV累计回款金额变动';"
];

const SYNC_MARKER = { table: 'b_transaction_indicator', column: 'fund', comment: '基金名称-3' };

async function isPerformanceExportCommentsSynced(dbPool) {
  const [rows] = await dbPool.query(
    `SELECT COLUMN_COMMENT FROM INFORMATION_SCHEMA.COLUMNS
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? AND COLUMN_NAME = ?
     LIMIT 1`,
    [SYNC_MARKER.table, SYNC_MARKER.column]
  );
  return rows[0]?.COLUMN_COMMENT === SYNC_MARKER.comment;
}

async function applyPerformanceExportColumnComments(dbPool) {
  if (await isPerformanceExportCommentsSynced(dbPool)) {
    return;
  }
  console.log('  → 同步业绩看板导出表字段 COMMENT（首次约需 1～3 分钟，请耐心等待）…');
  let applied = 0;
  for (const sql of ALTER_SQL) {
    try {
      await dbPool.query(sql);
      applied += 1;
    } catch (e) {
      /* 单字段失败不影响其余 COMMENT 同步 */
    }
  }
  console.log(`  ✓ 业绩看板导出表字段 COMMENT 已同步（${applied}/${ALTER_SQL.length}）`);
}

module.exports = { applyPerformanceExportColumnComments };
